### ISSUE TITLE
Discrepancies Between SDK Models and API Documentation

### ISSUE THREAD

**Issue by lucasrafagnin** [pluggyai/pluggy-java#52]
Olá pessoal, 

Tem alguns atributos presentes na documentação da API: https://docs.pluggy.ai/reference/accounts-list

E que não constam nos modelos da SDK, por exemplo:

`creditData.status`
`creditData.holderType`
`bankData.automaticallyInvestedBalance`

No caso a documentação que está desatualizada ou o SDK?

**Comment by lucasrafagnin** [comment]
Hi guys @NicolasMontone @FranDisalvo90 

I noticed that some attributes mentioned in the API documentation are missing in the SDK models, such as:

```
creditData.status
creditData.holderType
bankData.automaticallyInvestedBalance

```
I would be happy to contribute and make the necessary adjustments to align the SDK with the API. May I go ahead and open a PR for this?

Also, I would need a few keys, such as `RSA_PUBLIC_KEY`, to run the unit tests. Could you please provide those?

Thanks!

**Comment by NicolasMontone** [comment]
> Hi guys @NicolasMontone @FranDisalvo90 
> 
> 
> 
> I noticed that some attributes mentioned in the API documentation are missing in the SDK models, such as:
> 
> 
> 
> ```
> 
> creditData.status
> 
> creditData.holderType
> 
> bankData.automaticallyInvestedBalance
> 
> 
> 
> ```
> 
> I would be happy to contribute and make the necessary adjustments to align the SDK with the API. May I go ahead and open a PR for this?
> 
> 
> 
> Also, I would need a few keys, such as `RSA_PUBLIC_KEY`, to run the unit tests. Could you please provide those?
> 
> 
> 
> Thanks!

Hey! You can open a PR directly I will be super happy to review it 🫡.
Don't worry about the tests, I will work in some future to make them work locally without the keys

**Comment by lucasrafagnin** [comment]
Hi, done: https://github.com/pluggyai/pluggy-java/pull/53

**Comment by NicolasMontone** [comment]
Thanks a lot! Already deployed the new tag 1.4.0! https://github.com/pluggyai/pluggy-java/releases/tag/v1.4.0
